### ISSUE TITLE
C# plugins need server restart to be updated

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#10]
Well, as a C# plugin developer, this annoys me a lot.

I have to shutdown the server and start it again to include the changes to C# plugins to the server.

Thanks,

Snake.

**Comment by balu92** [comment]
You can reload them if you change the assembly version, which can be done automatically with every compilation, by adding 2 lines to your plugin. But that way you will have more version loaded of the same namespace.
