### ISSUE TITLE
chat.say exceptions not written in the logs

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#11]
Sometimes, the chat.say exceptions aren't printed on the logs.

**Comment by mikecrews** [comment]
In Fougerite.cfg debug logging is off by default in recent (MC5+) Fougerite releases.  Are you sure you have it enabled?

The exception details will be in the Fougerite Logs directory, which is in the same place as the PublicFolder.  The Rust server log and console will only show the error message, which is still enabled by default.

**Comment by SnakeTheRipper** [comment]
Yes, they were enabled, but console just showed chat.say exception blabla, no full exception, and logs didn't neither.

Found that sometimes string.Join used badly makes that.

**Comment by mikecrews** [comment]
The Console class catches exceptions before we can, so the logs we get are all we can get.
