### ISSUE TITLE
Wiper

### ISSUE THREAD

**Issue by Rahulsinghz** [Notulp/Fougerite#125]
Once added wiper in server One c4 can blow up all base 
![wiper setting](https://user-images.githubusercontent.com/34271188/54496577-1b121980-48f1-11e9-8bd2-a9709cf1c370.png)
here is wiper setting 
Is there something i am missing or not doing right?
or there is some changes needed to be added

"Once C4 on any wall can break a full base"= main problem

**Comment by dretax** [comment]
There is no EntityHurt event registered at Wiper, so there is nothing to modify the damage.
https://github.com/dretax/Wiper/blob/master/Wiper/Wiper.cs
