### ISSUE TITLE
Death message new update

### ISSUE THREAD

**Issue by Rahulsinghz** [Notulp/Fougerite#130]

**Comment by Rahulsinghz** [comment]
![image](https://user-images.githubusercontent.com/34271188/55683675-92602980-5942-11e9-8feb-ba245d985c78.png)

once loaded the plugin there is an error also the 2 .ini files do not match on the website and the downloaded file

**Screenshot from website:**
![image](https://user-images.githubusercontent.com/34271188/55683688-bf144100-5942-11e9-8b3d-9dfd4b64b5dd.png)

**Screenshot of actual.ini File in new download**:
![image](https://user-images.githubusercontent.com/34271188/55683701-ea972b80-5942-11e9-947f-c643018d0c4f.png)

**Comment by dretax** [comment]
@Rahulsinghz does the downloaded file also throw errors?

**Comment by Rahulsinghz** [comment]
yes the error posted in the above comment is from the latest build downloaded

**Comment by Rahulsinghz** [comment]
Issue fixed after the patch
