### ISSUE TITLE
Hook on Fougerite.Logger

### ISSUE THREAD

**Issue by SPooCK** [Notulp/Fougerite#137]
Hi DreTax,

As per request in Discord from you, I'm posting my request to create a hook on when Fougerite. Logger is called. I have an example function that works fine for me and hopefully you can integrate something similar when you have the time.

```
Application.RegisterLogCallback(new Application.LogCallback(OnConsoleLog));
private void OnConsoleLog(string condition, string stackTrace, LogType type) {
       ConsoleSystem.Print(condition);
       //Possibly add here hook like: Hooks.OnConsoleLog(condition, stackTrace, type)
}
```

Thanks,
SPooCK

**Comment by dretax** [comment]
I'm not sure if this is still relevant, but I'll do it this weekend just for fun.

**Comment by dretax** [comment]
https://github.com/Notulp/Fougerite/pull/141/commits/ab59d68f648ad62d0c1868b1c73ebd7b8c25183b
