### ISSUE TITLE
Cheater Flooder Errors

### ISSUE THREAD

**Issue by VictorS007** [Notulp/Fougerite#139]
Hello, users are using cheat to take down my server, I need a fix!
![unknown](https://user-images.githubusercontent.com/56007560/74390719-e2204480-4de0-11ea-8d0c-9c4b570d9518.png)

**Comment by dretax** [comment]
@VictorS007 Expect a fix on the weekend, I am extremly busy.

**Comment by dretax** [comment]
#140
