### ISSUE TITLE
NavMesh error spam

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#15]
The server gets spammed with NavMesh errors. I've tried on several machines and the Equinox rust legacy server has them too (i've seen them from Rusty).

http://dretaxmc.eu/snakescreen/fullerror.png

**Comment by SnakeTheRipper** [comment]
We found a way to make it stop and for now works quite good : 
http://fougerite.com/resources/navmeshfixer.95/

**Comment by dretax** [comment]
Referencing: https://github.com/dretax/Python-Plugins/blob/master/NavMeshRunner/NavMeshRunner.py is the correct way of eliminating this.
