### ISSUE TITLE
Fougerite Console going crazy sometimes

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#21]
I don't know how to replicate this, just happens.

http://dretaxmc.eu/snakescreen/dafuqrust.swf

**Comment by mikecrews** [comment]
dupe of https://github.com/Notulp/Fougerite/issues/15

**Comment by SnakeTheRipper** [comment]
I meant the fact that when you write a new line appears on top of that line, with the previous message, not the NavMesh error spam.

**Comment by mikecrews** [comment]
Also, Shockwave Flash - are you fucking kidding me?

**Comment by balu92** [comment]
I think it's a bug with rust's server console, maybe unity!?
And yeah, you could write the issue down in 1-2 sentence or just upload a picture of it.
http://i.imgur.com/c59tpkj.png

**Comment by SnakeTheRipper** [comment]
Well, Jing offers making a photo or a video. I thought it would be cooler to show it on a video. When you record the video, Jing autocreates the shockwave flash and uploads it.

**Comment by dretax** [comment]
Whats the problem with swf? I dont get It......-.-
