### ISSUE TITLE
Fougerite Path

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#23]
If the server path has many spaces or any other non ascii characters, then the server will go crazy. I don't know how critical is this, I just thought I would give a notice.

**Comment by mikecrews** [comment]
"go crazy" needs to be a specific problem with symptoms you can reproduce when the same conditions occur.

**Comment by dretax** [comment]
I gotta say that this was a long time ago. Maybe even UTF8 chars break It. I'm not sure, but I gotta test It.

**Comment by mikecrews** [comment]
Windows pathnames can contain UTF8 characters, except for the reserved characters / : ? * and so on.

**Comment by dretax** [comment]
Hummmmmmmmmm. I think we can close this.
