### ISSUE TITLE
Error line location?

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#24]
Is It possible to print the line where the error occured in the plugins?
I remember Riketta did enable It for Magma before, but It's the same on all the current engines. I guess It's possible, would It be hard?

**Comment by balu92** [comment]
IPM already does this. Don't know if jint can do it.

**Comment by dretax** [comment]
Hummmm

**Comment by mikecrews** [comment]
You mean like this:
[12/17/2014 1:21:46 AM] [Exception] [ JintPluginModule->LoadPlugin | JintPluginModule->ReloadPlugins | JintPluginModule->Initialize | ModuleContainer->Initialize | ModuleManager->LoadModules | Bootstrap->Start | ]
Jint.Parser.ParserException: **Line 15:** Unexpected token var

**Comment by dretax** [comment]
Yes. It's seems that I can't find the line location in IPM errors balu.

**Comment by dretax** [comment]
http://pastie.org/private/bfuav24txplyeoili6bzg

That's your plugin's error which I just got from somebody. It's obvious where we can find the error, but what about this one?

http://pastie.org/private/qety8vqyi8lrmqzmozx1w

**Comment by mikecrews** [comment]
If the error occurs in .Net code, you will only get the plugin function name that called the .Net code that threw the exception.

If the error occurs in plugin code - such as undeclared variable, object has no method, etc. then the line of the plugin code would be identified.

**Comment by dretax** [comment]
I see

**Comment by balu92** [comment]
Are you sure, you are using the latest version?
https://github.com/balu92/IronPythonModule/commit/d99f995aebd8ea1aaa9bc579a9471d8282ee9fb0#diff-a9dd21f4708d2274d871c5af337dfcf8L53
