### ISSUE TITLE
HurtEvent returning true regardless (IsStructure + IsDeployableObject)

### ISSUE THREAD

**Issue by jakkee** [Notulp/Fougerite#26]
HurtEvent.Event.IsStructure / IsDeployableObject return true regardless of the item
I tried the following on Beds, Chests, Campfires, Walls, Foundations all returning true for both codes.

    def On_EntityHurt(self, HurtEvent):
            if HurtEvent.Entity.IsStructure:
                Player = HurtEvent.Attacker
                Player.Message("Structure: " + HurtEvent.Entity.Name)

    def On_EntityHurt(self, HurtEvent):
            if HurtEvent.Entity.IsDeployableObject:
                Player = HurtEvent.Attacker
                Player.Message("Deployable: " + HurtEvent.Entity.Name)

**Comment by dretax** [comment]
Are you a 100% on this issue? Since I'm using this method in 2 plugins.

def GetIt(self, Entity):
        try:
            if Entity.IsDeployableObject():
                return Entity.Object.ownerID
            if Entity.IsStructure():
                return Entity.Object._master.ownerID
        except:
            return None

It's returning me the ownerID as It should.

**Comment by jakkee** [comment]
For myself it returns true regardless the item

**Comment by dretax** [comment]
Hummm

**Comment by mikecrews** [comment]
These methods have not changed since they were imported from Magma.

https://github.com/Notulp/Fougerite/blob/b84a7a1be3092e7cc5af62ef42e5c8b0c15141d1/Fougerite/Fougerite/Entity.cs#L84-L92
