### ISSUE TITLE
Sleepers seem to be NPCs

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#30]
Recently I noticed that Sleepers are not entities.

Shame on me.

Seems like hitting a Sleeper runs on PlayerHurt event, but since the mod cannot find the player the hurtevent assigns It as an NPC.

Here is my code: http://pastie.org/private/cfkpmcpidyxunod7pefbjq

Output:
http://dretaxmc.eu/dretaxscreen/2015-01-18_1553.png

I think the Sleeper It self is not an NPC. Hitting the NPC doesn't run the EntityHurt event, so my SleeperLog plugin is obsolete. Any ideas?

**Comment by balu92** [comment]
let's see the result of:
repr(HurtEvent.Victim.Character)
repr(HurtEvent.Victim)

**Comment by dretax** [comment]
I will test It soon.

**Comment by mikecrews** [comment]
Sleepers (SleepingAvatar is the actual class name) are DeployableObject.  If you want to discover the particular type of DeployableObject an Entity is, call Entity.Object.GetType().ToString().

**Comment by dretax** [comment]
Interesting. It seems like the Sleeper is some kind of Entity/Player mix? I will test both stuff today.

**Comment by balu92** [comment]
It is DeployableObject not a Player:
public class SleepingAvatar : DeployableObject, IServerSaveable {}

**Comment by dretax** [comment]
Don't ask me. Just tested It with snake, there is a sleeper on the ground which is an actual player. Hit It, and It will run with HurtEvent

**Comment by SnakeTheRipper** [comment]
Indeed !

**Comment by dretax** [comment]
Picture:
http://dretaxmc.eu/dretaxscreen/2015-01-21_2115.png

Code:
https://gist.github.com/dretax/a6fc22a453c40fdcb3e4

**Comment by mikecrews** [comment]
Working as intended.  From Fougerite\Events\HurtEvent.cs:

```csharp
            Fougerite.Player player2 = Fougerite.Player.FindByPlayerClient(d.victim.client);
            if (player2 != null)
            {
                this.Victim = player2;
            }
            else
            {
                this.Victim = new NPC(d.victim.character);
            }
```

**Comment by dretax** [comment]
So calling HurtEvent.Entity on playerhurtevent should work?

**Comment by mikecrews** [comment]
https://github.com/Notulp/Fougerite/issues/31
