### ISSUE TITLE
SingleBed and SleepingBagA 

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#33]
Seems like these two entities do not fire the Entity hurtevent when we are damaging them. I'm 100% sure on this, we shot the bed or the bag until It disappeared. Any ideas?

**Comment by SnakeTheRipper** [comment]
Tested and confirmed.

**Comment by mikecrews** [comment]
DebugLog will log every damage event Fougerite receives, using its custom ToString() format:
string format = "{{attacker={3}, victim={0}, amount={1}, status={2}, sender={4}}}";
That should help decide what's really going on.
22afde26ffb1acb765a7cb5c9062447c6c810fb7

**Comment by mikecrews** [comment]
SingleBed, SleepingBagA, and AvatarMale classes extend DeployableObject which has the OnHurt() method Fougerite patched into.  But when TakeDamage class fires a message SendMessage("OnHurt") to those objects, the hook isn't called.

**Comment by dretax** [comment]
You said you will patch something to the assembly?
