### ISSUE TITLE
DataStore flood.

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#34]
Ehhh. I'm getting flood with this:

http://dretaxmc.eu/dretaxscreen/2015-01-26_1715.png

**Comment by mikecrews** [comment]
Yes, you're using Zone3d.  Fix has been committed.  Zone3d uses its own Hashtable, separate from DataStore.

https://github.com/Notulp/Fougerite/commit/75fa095acde6796f2ca87314063fc26461f1dc90
https://github.com/Notulp/Fougerite/commit/8e6429f1e6f69db0ee2303e118c208bfc0b75597
