### ISSUE TITLE
WildLife

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#35]
Might be connected with the sh*tty NPC errors, but worths a look.

http://pastie.org/private/sdmtrtoipq3uim1n28dia

**Comment by mikecrews** [comment]
I don't see any Fougerite in that.

**Comment by dretax** [comment]
Yeah It probably the bugged NPCs underground. I have a code for you that we might able to add to Fougerite. Interested?

**Comment by dretax** [comment]
The patcher that we got for this is being tested and It runs good. I told balu to get you the code that needs to be in the patcher. Don't forget to ask him.
