### ISSUE TITLE
GetDooratCoords in Util

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#38]
As I see we changed that method.

Error: http://fougerite.com/threads/auto-doors.438/page-2#post-4599

**Comment by mikecrews** [comment]
can you link the commit where it changed please

**Comment by dretax** [comment]
https://github.com/Notulp/Fougerite/commit/bd981518c87385a0e2aa2f7f3efe20054f0caf58 ?

**Comment by mikecrews** [comment]
Interesting.  Is the .Equals method of Vector3 not working as advertised?  I read the docs and looked at the code. Vector3.Equals() is supposed to allow for some fuzziness due to rounding and floating point precision.  It's the recommended way to compare, rather than .Distance(smallnumber).

**Comment by dretax** [comment]
Humm.

**Comment by mikecrews** [comment]
So, is it not working, or... ?

**Comment by dretax** [comment]
Nope. It just throws that error.

**Comment by mikecrews** [comment]
Returned to distance < 2f method in commit: 362725bab2ad1cec732f38d9472a390f033dad5b
