### ISSUE TITLE
NPC Location

### ISSUE THREAD

**Issue by jakkee** [Notulp/Fougerite#39]
~NOT AN ISSUE~
Getting an NPC's location either as Vector or X, Y, Z would be handy as I was looking at spawning a loot bag when non rad animals are killed rather than doing Raycasting.
Could be used for other things such as finding the distance between the player and NPC (AntiCheat).

**Comment by balu92** [comment]
you can use: npc.Character.transform.position(.x/.y/.z)

**Comment by dretax** [comment]
Yeah balu, I already told him. But hey, why not? :D

**Comment by mikecrews** [comment]
af98ac149a474cf18b0e0a26d08d34e106f98d4d
