### ISSUE TITLE
Add plugin version on exception throw

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#40]
I think it would be cool to print the plugin version when an exception is thrown, most of the times people have outdated versions and they make plugin developers loose time.

**Comment by mikecrews** [comment]
How does Fougerite get your plugin version?

**Comment by balu92** [comment]
You can get the assembly version of modules (c# plugins):
https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/Module.cs#L25

As for scripts (.js, .py), the hosting module would need to implement a way for plugins to register their version.

**Comment by SnakeTheRipper** [comment]
Indeed, C# modules have a "public override Version Version", I don't know py or js.

**Comment by mikecrews** [comment]
There isn't anything for script plugins.  If someone wants to write one, please submit a PR when you have it working.

**Comment by dretax** [comment]
C# plugins can be implemented.

Python Scripts always have a __version__.

Js............

**Comment by SnakeTheRipper** [comment]
Well then we can make something for Python and C#.
