### ISSUE TITLE
NPC Killed Fougerite Hook Null Exception

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#46]
http://pastie.org/private/vzqtktwiteffudorwkua

https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/NPC.cs#L18

This seems to be causing nullpointer exception in Fougerite. Any ways to fix this?

**Comment by balu92** [comment]
I assume that in a 'new DamageEvent()' the attacker and victim are null.
I think there is no point in raising events with null attacker and null victim, so we should just return [before this line](https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/Hooks.cs#L259) and probably in other EntityHurt events as well.

**Comment by dretax** [comment]
@mikecrews Can we fix this before we release the 1.0.8 Pre release?

**Comment by mikecrews** [comment]
Looks like I already did. 22afde26ffb1acb765a7cb5c9062447c6c810fb7

**Comment by dretax** [comment]
Thanks.
