### ISSUE TITLE
AntiCheat Client

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#5]
The AntiCheat is a major secondary enchantment for the upcoming client.

By my suggest the AntiCheat client should contain the following:

* Some of the Cheats are requiring to be in the main folder of Rust. It's an easy thing to make sure to bypass those.

* Client should be launching Rust It self, making sure that It won't load If Rust wasn't started by the client It-self.

* Probably hard work, but after that option we could possible catch the injection or the program that injects.

* Security measurements to make sure nothing is going to be faked on the connection to the server

* Optional Requirement of the client

* Make sure that the player is not able to leave from the anticheat, If It does, then make sure to drop the connection of the player from the server, If the server lost the packets, or just destroy rust immediately at that moment. Both possibly a good idea.

* Optional random timed game only screenshot sending method for the server. All the screenshots would be stored in folder named as the player's steamid. This could really give a huge option to the administration team to check whos hacking.

* Wheather we want to inject into the game, or just to patch the assembly, that will require checking all the time. Making a hack that will make the assembly get reverted or something like that is kinda possible.

Edit:

* We might want to add some extra identification in the client. Ofc, I don't mean It, but what if we add a processor ID property into fougerite and the client?

**Comment by SnakeTheRipper** [comment]
On the way :package:
