### ISSUE TITLE
Sleepers

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#53]
https://github.com/Notulp/Fougerite/issues/31

It seems like It's not calling any events now as It used to.

**Comment by dretax** [comment]
If we could somehow make the sleeper an entity, I could do something with It.

**Comment by mikecrews** [comment]
There is no problem wrapping Sleepers in Entity.  Sleepers have always been wrapped in Entity in World.Entities. 

Sleepers simply don't generate a DamageEvent.  Neither do Sleeping Bag or Beds.

**Comment by dretax** [comment]
Ahh right. So that means that when you hit a sleeper the game detects It, but It won't pass the required parameters that I would like to see?
