### ISSUE TITLE
CodecsInfo

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#56]
https://bugs.launchpad.net/ubuntu/+source/dlr-languages/+bug/598411

4/4/2015 6:33:57 PM] [Debug] [CHAT-CMD] "atapka" executed "/sethome ház"
[4/4/2015 6:33:57 PM] [Error] Traceback (most recent call last):
  File "<string>", line 464, in On_Command
SystemError: An exception was thrown by the type initializer for CodecsInfo

Using non-ascii characters in commands causes errors. Any way to fix?

**Comment by mikecrews** [comment]
Yes, the fix is in the link you posted.  Let me know how it works.

**Comment by dretax** [comment]
Unable to fix. A simple plugin that clears the crap characters out can do it though.
