### ISSUE TITLE
Zone3D Contains is broken

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#58]
Zone3D seems to be broken in some ways.

https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/Zone3D.cs#L31

Doesn't matter how many debugs did I do. http://pastie.org/private/jx4b4svfg8icu3zv0louyw

It just didn't make It work. Don't know why. It just returns false

**Comment by weberiz** [comment]
Maybe its a problem with thread? loom
