### ISSUE TITLE
OnPreCommand event

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#62]
This event should be fired before OnCommand events. It should allow cancelling the OnCommand event.

It's usefull when you want some commands to be restricted.

For example :

In a hunger games event, you shouldn't be able to teleport. OnPreCommand would check the command and cancel it.

**Comment by balu92** [comment]
In pluton we have "On_CommandPermission", I might add something like that to fougerite too, but currently I'm too busy with irl stuff I can't contribute much to pluton either at the moment. I'll get back to pluton and fougerite ASAP, but I won't even have a pc at the beginning so... I guess @mikecrews can and will implement it before I do.

**Comment by dretax** [comment]
I know It's not the thing that we wanted, but this should do It for now.

https://github.com/Notulp/Fougerite/blob/dretax/Fougerite/Fougerite/Server.cs#L18
