### ISSUE TITLE
1.5.5 When player remove something..

### ISSUE THREAD

**Issue by salvadj1** [Notulp/Fougerite#65]
No NGC View with id NGC ViewID 89194518 (1361:23) to send RPC "ClientHealthUpdate"

**Comment by dretax** [comment]
Remove what exactly?

**Comment by salvadj1** [comment]
That happens in version 1.5.5 when some player removes a parts of the structure (wall, pillar, etc) even when using c4, but yesterday when you did the tests of the sleepers I think it was solved!

**Comment by dretax** [comment]
Might have fixed before, just didn't remember. We will see after the release.

**Comment by salvadj1** [comment]
Fixed!
