### ISSUE TITLE
Idea: MySQL support

### ISSUE THREAD

**Issue by NewAgeCZ** [Notulp/Fougerite#66]
Could you please add MySQL to the server?

**Comment by dretax** [comment]
Seems like there is something wrong when using the dlls, will see if I can or somebody can come up with something..

https://stackoverflow.com/questions/44538705/typeload-exception-on-mysql-net-3-5

**Comment by NewAgeCZ** [comment]
I found someone suggesting to add I18N dlls.
Check this https://forum.unity3d.com/threads/typeloadexception-with-dll-files.148361/

**Comment by dretax** [comment]
"Copy the "System.Data.dll" from "C:\Program Files (x86)\Unity\Editor\Data\Mono\lib\mono\unity" to the DLL's folder you use in your project tree"

The Unity versioned System.Data did the trick without using the I18N, thanks for the assist.

**Comment by dretax** [comment]
Had to add the System.Management 2.0 dll for this to work, but according to the debug logs, mysql could connect. The usage will be up to you. =)
