### ISSUE TITLE
Unshare Bug!

### ISSUE THREAD

**Issue by Assassini** [Notulp/Fougerite#70]
Hi
if there is player with this name: Mike
if you use /share Mike  he is now in your sharelist and he can open your doors!but if Mike Changes his name to Miky!! if you use /unshare Mike /unshare Miky /unshare [His Steamid] he will not Unshare!!He Is Stay sharing!!!plz fix it

**Comment by dretax** [comment]
Would you test this?

**Comment by dretax** [comment]
https://www.mediafire.com/?24gbxqmio2t3lwq

**Comment by Assassini** [comment]
i will test it in my server and say it is ok or not
tnx

**Comment by Assassini** [comment]
Every Thing Is OK!
Thank you a lot...
Can You Add Share List ?
Some Players may forgot who is in their share list!

**Comment by dretax** [comment]
Yes.
