### ISSUE TITLE
Combine plugin folders into one

### ISSUE THREAD

**Issue by jakkee** [Notulp/Fougerite#73]
Combine JS/Py/LUA into just one Plugins folder (More user friendly)
Have a separate folder for data (INI settings, etc)
Basically the same as Oxide, Very easy to use and user friendly

**Comment by dretax** [comment]
Possible.

**Comment by jakkee** [comment]
I might work on this

**Comment by dretax** [comment]
It might be implemented, or may not. The structural change in 1.7.0 made It so. C# might go also in the Save folder, however not all plugins will be in the same folder.
