### ISSUE TITLE
Update permissions system

### ISSUE THREAD

**Issue by jakkee** [Notulp/Fougerite#75]
Update permissions system, Similar to Oxide. Add permissions to users/groups
(RUST++ or new module)

**Comment by wilywork** [comment]
I'll check to add my permissions plugin in fougerite

**Comment by jakkee** [comment]
I will merge this https://github.com/jakkee/FougeritePlugins/blob/master/CSharpPlugins/Permissions/Permissions.cs
into either Fougerite or Rust++ once it has had a bit of love
