### ISSUE TITLE
Rust game crashes - happens often

### ISSUE THREAD

**Issue by neals93** [Notulp/Fougerite#85]
[error.log](https://github.com/Notulp/Fougerite/files/1817323/error.log)
[output_log.txt](https://github.com/Notulp/Fougerite/files/1817324/output_log.txt)

**Comment by dretax** [comment]
I am aware of this, I will take a look at It.
AFAIK it only happens on  exit?

**Comment by neals93** [comment]
It happens at any moment from when I boot the game, so it could happen from the moment I start rust buster or I could get lucky and it may not occur for an hour.

The error has happened 20+ times to me now, it's the reason I've chosen to post it up here.

Thanks

**Comment by dretax** [comment]
Can you upload me the RustBuster.log too?
