### ISSUE TITLE
RPC that crashes the server (does not happen in version 1.62b)

### ISSUE THREAD

**Issue by salvadj1** [Notulp/Fougerite#87]
https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/Hooks.cs#L2666 

 It is generating many problems and the CRASH server quite often, apparently does not end the player's kick and enters an infinite loop that makes the server CRASH completely

![unknown](https://user-images.githubusercontent.com/24988418/38771558-804d82c4-4025-11e8-8b69-8dbc64cc9bb7.png)

**Comment by dretax** [comment]
@salvadj1 I need a better image.
