### ISSUE TITLE
1.6.5 fougerite Ulink broken

### ISSUE THREAD

**Issue by weberiz** [Notulp/Fougerite#95]
server crashed:
![image](https://user-images.githubusercontent.com/11724698/42712146-2542cd2a-86f3-11e8-8411-92570aef7190.png)
and again crashed:
![image](https://user-images.githubusercontent.com/11724698/42712181-46946812-86f3-11e8-8e46-6bcf719f4f43.png)
1 time error:
![image](https://user-images.githubusercontent.com/11724698/42712197-57a67028-86f3-11e8-91ac-7bc7d0787203.png)

**Comment by dretax** [comment]
1.6.6 might be the answer for this. Test.
