### ISSUE TITLE
Add /sharelist to RustPP

### ISSUE THREAD

**Issue by TheMajical** [Notulp/Fougerite#98]
Many players ask server owners for /sharelist because they want to know who they shared
plz add /sharelist

**Comment by BogdanWDK** [comment]
Will do it

**Comment by dretax** [comment]
Although Rust++ is fairly an outdated platform we have used in the past, we never really got rid of it sadly.
Implemented.

**Comment by dretax** [comment]
https://github.com/Notulp/Fougerite/pull/141/commits/65aa3bb4994acb4f3430501bb1688231a01669b8
